kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
 apiServerAddress: "10.0.0.176"
 apiServerPort: 6443
 disableDefaultCNI: true        # do not install kindnet
 kubeProxyMode: none            # do not run kube-proxy
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
